# Generated by Django 5.0.6 on 2024-05-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aadhaar_number", models.CharField(max_length=12, unique=True)),
                ("image", models.ImageField(null=True, upload_to="user_images/")),
            ],
        ),
        migrations.CreateModel(
            name="VoterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, null=True)),
                ("aadhar", models.CharField(max_length=50, null=True)),
                ("otp", models.CharField(max_length=5, null=True)),
                ("status", models.CharField(default="Pending", max_length=20)),
            ],
            options={
                "db_table": "voters_details",
            },
        ),
        migrations.CreateModel(
            name="ElectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("election_name", models.CharField(max_length=100)),
                ("election_head", models.CharField(max_length=100)),
                ("election_date", models.DateField()),
                ("election_picture", models.ImageField(upload_to="images/")),
                ("constituency", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=10)),
                ("candidates_count", models.IntegerField(default=0)),
                ("successful_votes", models.IntegerField(default=0)),
                ("unsuccessful_votes", models.IntegerField(default=0)),
                ("voters", models.ManyToManyField(to="adminapp.votermodel")),
            ],
            options={
                "db_table": "elction_detials",
            },
        ),
        migrations.CreateModel(
            name="CandidateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_name", models.CharField(max_length=100)),
                ("party_name", models.CharField(max_length=100)),
                ("symbol", models.ImageField(upload_to="symbols/")),
                ("votes", models.IntegerField(default=0)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="election_candidates",
                        to="adminapp.electionmodel",
                    ),
                ),
                (
                    "voters",
                    models.ManyToManyField(
                        related_name="voted_voters", to="adminapp.votermodel"
                    ),
                ),
            ],
            options={
                "db_table": "candidate_details",
            },
        ),
        migrations.CreateModel(
            name="VotesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_block", models.CharField(max_length=100)),
                ("candidate_block", models.CharField(max_length=100)),
                ("election_block", models.CharField(max_length=100)),
                (
                    "candidate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates_votes",
                        to="adminapp.candidatemodel",
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="election_votes",
                        to="adminapp.electionmodel",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voter_voted_list",
                        to="adminapp.votermodel",
                    ),
                ),
            ],
            options={
                "db_table": "votes",
            },
        ),
    ]
