# Generated by Django 5.0.6 on 2024-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="fingerprint_image",
            field=models.ImageField(null=True, upload_to="fingerprints/"),
        ),
    ]
