# Generated by Django 5.0.6 on 2025-03-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_voter_fingerprint_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votermodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='votermodel',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
