# Generated by Django 5.0.6 on 2025-03-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_remove_votermodel_phone_votermodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='fingerprint_image',
        ),
    ]
